on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SSH_PATH }}
            sudo composer require stape/gtm-server-side-magento-module dev-dev
            sudo php bin/magento setup:upgrade
            sudo php bin/magento setup:di:compile
            sudo php bin/magento setup:static-content:deploy -f
            sudo chown -R www-data:www-data var/
